Mailbox2channel
fsharplang-ru/pulsar-client-dotnet pull request #181
Opened 2021-08-19 11:46 UTC by TiraelSedai

PR for issue: Change all mailboxes to channels to improve performance #168

2021-08-20 20:55 UTC, Lanayx commented on src/Pulsar.Client/Internal/ConsumerImpl.fs
> +    | HasMessageAvailable of TaskCompletionSource<Task<bool>>
It's essentially Task<Task>, can we leave just one?

2021-08-20 21:01 UTC, Lanayx requested changes

2021-08-20 21:01 UTC, Lanayx commented on src/Pulsar.Client/Internal/ConsumerImpl.fs
> +    | Acknowledge of MessageId * AckType * Transaction option * TaskCompletionSource<Task<Unit>> option
It's essentially `Task<Task>`, can we leave just one?

2021-08-20 21:01 UTC, Lanayx commented on src/Pulsar.Client/Internal/ConsumerImpl.fs
> +    | ReconsumeLater of Message<'T> * AckType * TimeStamp * TaskCompletionSource<Task<unit>>
It's essentially `Task<Task>`, can we leave just one?

2021-08-20 21:01 UTC, Lanayx commented on src/Pulsar.Client/Internal/MultiTopicsConsumerImpl.fs
> +    | NegativeAcknowledge of TaskCompletionSource<Task<unit>> * MessageId
It's essentially `Task<Task>`, can we leave just one?

2021-08-20 21:01 UTC, Lanayx commented on src/Pulsar.Client/Internal/MultiTopicsConsumerImpl.fs
> +    | AcknowledgeCumulative of TaskCompletionSource<Task<unit>> * MessageId * Transaction option
It's essentially `Task<Task>`, can we leave just one?

2021-08-20 21:01 UTC, Lanayx commented on src/Pulsar.Client/Internal/MultiTopicsConsumerImpl.fs
> +    | Acknowledge of TaskCompletionSource<Task<unit>> * MessageId * Transaction option
It's essentially `Task<Task>`, can we leave just one?

2021-08-20 21:01 UTC, Lanayx commented on src/Pulsar.Client/Internal/MultiTopicsConsumerImpl.fs
> +    | RedeliverUnacknowledged of RedeliverSet * TaskCompletionSource<Task>
It's essentially `Task<Task>`, can we leave just one?

2021-08-20 21:01 UTC, Lanayx commented on src/Pulsar.Client/Internal/TaskSeq.fs
> +    | WhenAnyTask of TaskCompletionSource<Task<Task<'T>>>
It's essentially `Task<Task>`, can we leave just one?

2021-08-27 18:47 UTC, merged

2021-08-27 19:00 UTC, TiraelSedai commented on src/Pulsar.Client/Internal/ConsumerImpl.fs
> +    | HasMessageAvailable of TaskCompletionSource<Task<bool>>
Done.

2021-08-27 19:01 UTC, TiraelSedai commented on src/Pulsar.Client/Internal/ConsumerImpl.fs
> +    | Acknowledge of MessageId * AckType * Transaction option * TaskCompletionSource<Task<Unit>> option
This one couldn't be done easily.

2021-08-27 19:01 UTC, TiraelSedai commented on src/Pulsar.Client/Internal/ConsumerImpl.fs
> +    | ReconsumeLater of Message<'T> * AckType * TimeStamp * TaskCompletionSource<Task<unit>>
I haven't had a chance to look at it and I suggest to look at it in the separate PR

2021-08-27 19:01 UTC, TiraelSedai commented on src/Pulsar.Client/Internal/MultiTopicsConsumerImpl.fs
> +    | AcknowledgeCumulative of TaskCompletionSource<Task<unit>> * MessageId * Transaction option
I haven't had a chance to look at it and I suggest to look at it in the separate PR

2021-08-27 19:01 UTC, TiraelSedai commented on src/Pulsar.Client/Internal/MultiTopicsConsumerImpl.fs
> +    | Acknowledge of TaskCompletionSource<Task<unit>> * MessageId * Transaction option
I haven't had a chance to look at it and I suggest to look at it in the separate PR

2021-08-27 19:01 UTC, TiraelSedai commented on src/Pulsar.Client/Internal/MultiTopicsConsumerImpl.fs
> +    | RedeliverUnacknowledged of RedeliverSet * TaskCompletionSource<Task>
I haven't had a chance to look at it and I suggest to look at it in the separate PR

2021-08-27 19:01 UTC, TiraelSedai commented on src/Pulsar.Client/Internal/TaskSeq.fs
> +    | WhenAnyTask of TaskCompletionSource<Task<Task<'T>>>
I haven't had a chance to look at it and I suggest to look at it in the separate PR